apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: python-api
      tier: app
  replicas: 3
  template:
    metadata:
      labels:
        app: python-api
        tier: app
    spec:
      containers:
      - name: python-api-redis
        image: adrisalas/python-api-redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
      - name: redis
        image: redis:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379